#!/bin/bash
module load bioinfo/snakemake-7.8.1
path=$2 # result dir
config=$1 # config file
pipeline_path=$(dirname $0) # path of pipeline source

path="/work/gadam/msgenova/"
config="/work/gadam/msgenova"
pipeline_path="/work/gadam/msgenova"

#sbatch snakemake -p --snakefile ${pipeline_path}/Snakefile --config repo_script=${pipeline_path} --configfile $path/config_user --cluster-config ${pipeline_path}/cluster_config.json --cluster "sbatch --output {cluster.output} --error {cluster.error} --cpus-per-task {threads} --job-name {rule} --mem {resources.mem_mb} " --jobs 200 --latency-wait 90 --use-envmodules --use-conda --stats stat.json  --directory $path --conda-prefix $path >& snakemake.log

# usage function showing the options allowed in the script

usage() { echo "Usage: $0 [-c <configuration_file>] [-o <output_directory>]" 1>&2; exit 1; }

# getops alllows to loop other the argument to check their integrity

while getopts ":c:o:ar:" option;do
	# getopts OPTSTRING VARNAME [ARGS ...]
	# for OPTSTRING v= check for options -v without parameters
	#		v: = check for options with parameters
	#		vp = check for options -v -p and give errors
	#		:vp = check for options -v -p and silences errors
	case "${option}" in
		c)
			c=${OPTARG}
			echo "Configuration file: ${c}"
			;;
		o)
			o=${OPTARG}
			echo "Output directory: ${o}"
			;;
		#all the other argument -> use *
		*)
			echo "Other options have been written"
			usage
			;;
	esac
done
# shift parameters order with shift
shift $((OPTIND-1))

#Verify that all parameters are well written -> Verify of a string is empty or not
if [ -z "${o}" ] || [ -z "${c}" ] ; then
	usage
else
	sbatch snakemake -p --snakefile ${pipeline_path}/Snakefile --config repo_script=${pipeline_path} --configfile $path$c --cluster-config ${pipeline_path}/cluster_config.json --cluster "sbatch --output {cluster.output} --error {cluster.error} --cpus-per-task {threads} --job-name {rule} --mem {resources.mem_mb} " --jobs 200 --latency-wait 90 --use-envmodules --use-conda --stats stat.json  --directory $o --conda-prefix $o >& snakemake.log
	echo $o
	echo $c
	echo $path$c
	echo ${pipeline_path}
fi
echo "c= ${c}"
echo "o= ${o}"
