
# Quality control
## Read quality

<!-- <details> -->
<!--     <summary> multiqc report </summary> -->

<!-- ```{r multiqc} -->

<!-- htmltools::includeHTML(paste0(workspace,"/01_sequence_qc/SOJ_multiqc_trim.html")) -->

<!-- ``` -->
<!-- </details> -->


### Read cleaning :

Sequences were trimmed with Trimmomatic tools...

```{r trimmomatic}
trimmo <- paste0(workspace,"/01_sequence_qc/log/trimmomatic.log")
dat    <- read.table(text = gsub(" ","\t",readLines(trimmo)),  header=TRUE)
DT::datatable(dat,  rownames = FALSE, caption = "Read cleaning results",
              options = list(rownames = TRUE, pageLength = 10, scrollX = T, dom = 'tip'),class = 'cell-border stripe')
```



## Alignement

Sequences were aligned using BWA MEM (v?) ...

### Mapping rate

```{r mapping rate}
file <- paste0(workspace,"/02_mapping/flagstat/concatenate_flagstat.txt")
if(file.exists(file)){
    flagstat <- read.table(file, sep="\t", header=FALSE) %>%
      dplyr::mutate(mapped=V3-V4, mapped.ratio=round(mapped/(V2)*100,2)) %>% dplyr::select(-V3, -V4)
    names(flagstat) <- c("sample", "raw", "mapped", "mapped.ratio")

  }

DT::datatable(flagstat, options = list(rownames = TRUE, pageLength = 10, scrollX = T, dom = 'tip'),class = 'cell-border stripe',
              rownames = FALSE, caption = "???")

```

```{r}

#count
nbr.reads.melt <- flagstat %>% dplyr::select(sample, raw, mapped, mapped.ratio) %>% reshape2::melt(id = "sample", value.name = "nbr.reads")

# p <- ggplot(data = dplyr::filter(nbr.reads.melt, variable == "mapped.ratio"), aes(y=nbr.reads, x=variable)) + geom_boxplot()  +
#   xlab("") + ylab("% reads") + ggtitle("...")
# 
# print(p)
# 
# p <- ggplot(data = dplyr::filter(nbr.reads.melt, variable %in% c("raw", "mapped")), aes(y=nbr.reads, x=variable)) + geom_boxplot()  +
#   xlab("") + ylab("number of reads") + ggtitle("...")+theme_bw()
# 
# print(p)

p <- ggplot(data = dplyr::filter(nbr.reads.melt, variable %in% c("mapped.ratio", "mapped")), aes(x=nbr.reads, y=variable)) + geom_boxplot()  +
  xlab("") + ylab("") + ggtitle("Mapped reads per samples") + facet_wrap(variable~., scales = "free", ncol = 1) +
  theme(axis.text.y = element_blank(), axis.ticks.y = element_blank()) 

print(p)

```


### Coverage

```{r depth}

cov.list <- lapply(sample_sheet$sample, function(x){
  file <- paste0(workspace,"/02_mapping/coverage/", x, ".coverage")
  if(file.exists(file)){

    read.table(file, sep="\t") %>%  dplyr::filter(V4 > 1)  %>% dplyr::mutate(sample = x)
  }
})

cov <- purrr::reduce(cov.list, rbind)
colnames(cov) <- c("rname",	"startpos",	"endpos",	"numreads",	"covbases",	"coverage",	"meandepth",	"meanbaseq",	"meanmapq", "sample")
cov$coverage <- round(cov$coverage, 2)

p <-ggplot(data = cov) + geom_boxplot(aes(x=meandepth, y=rname)) + xlab("depth (X)") + ylab("") + ggtitle("Depth of coverage mean per samples") +
  theme(axis.text.y = element_blank(), axis.ticks.y = element_blank()) + 
  facet_wrap(rname~., scales = "free")

print(p)

p <-ggplot(data = cov) + geom_boxplot(aes(x=coverage, y=rname)) +  ylab("") + xlab("Coverage (%)") + ggtitle("Propotion of covered bases per sample") +
  theme(axis.text.y = element_blank(), axis.ticks.y = element_blank()) + scale_x_continuous(labels=function(x){sprintf("%.2f", x)}) + facet_wrap(rname~., scales = "free")

print(p)

```


